include "modules.conf"
include "mimetypes.conf"

server.document-root = "/var/www/html"

$SERVER["socket"] == ":443" {

ssl.engine = "enable"
ssl.pemfile = "/home/XznFpi4dVteIRG51awOX/ssl/live/www8.the-galley.uk/fullchain.pem"
ssl.privkey = "/home/XznFpi4dVteIRG51awOX/ssl/live/www8.the-galley.uk/privkey.pem"
ssl.openssl.ssl-conf-cmd = ("Ciphersuites" => "TLS_AES_128_GCM_SHA256")+("Protocol" => "-ALL, TLSv1.3, TLSv1.2")+("Curves" => "secp384r1")
ssl.disable-client-renegotiation = "enable"
ssl.use-compression = "disable" #The CRIME attack exploits compression so we need to disable that

proxy.balance = "hash"
proxy.server = (
"" => (
#xxxxWEBSERVERIPHTTPSxxxx
)
)
}
