#XXXXS3_REDIRECTIONXXXX

       <Location /XXXXASSETSXXXX>
            RequestHeader set Referer "https://XXXXREFERERXXXX"
            ProxyPreserveHost Off
            ProxyPass  https://XXXXS3_HOST_URLXXXX ttl=20 retry=5
            ProxyPassReverse  https://XXXXS3_HOST_URLXXXX
            RequestHeader set "Host" "XXXXS3_HOST_URLXXXX"
            RequestHeader unset Cookie
            ProxyErrorOverride On
            ErrorDocument 404 /2XXXXASSETSXXXX/%{REQUEST_URI}
       </Location>

       ProxyPreserveHost On
       ProxyPass /2XXXXASSETSXXXX "balancer://webservers_https"
       ProxyPassReverse /2XXXXASSETSXXXX "balancer://webservers_https"
