#RewriteRule "^/XXXXASSETSXXXX/(.*)$" "https://XXXXS3_HOST_URLXXXX/$1" [P]
<Location /XXXXASSETSXXXX>
            ProxyPreserveHost Off
            ProxyPass  https://XXXXS3_HOST_URLXXXX
            ProxyPassReverse  https://XXXXS3_HOST_URLXXXX
            RequestHeader set "Host" "XXXXS3_HOST_URLXXXX"
            RequestHeader unset Cookie
            #RequestHeader set X-Real-IP %{REMOTE_ADDR}s
            #RequestHeader set X-Forwarded-For %{REMOTE_ADDR}s
</Location>
