ServerName XXXXWEBSITE_URLXXXX

#XXXXMODSECURITYXXXX

<IfModule mod_ssl.c>
    <VirtualHost *:443>
        DocumentRoot /var/www/html
        RewriteEngine On

        SSLEngine on
        SSLProxyEngine on
        SSLProxyVerify none
        SSLProxyCheckPeerCN off
        SSLProxyCheckPeerName off
        SSLProxyCheckPeerExpire off
        SSLCompression off

        SSLCertificateFile       XXXXHOMEXXXX/ssl/live/XXXXWEBSITE_URLXXXX/fullchain.pem
        SSLCertificateKeyFile    XXXXHOMEXXXX/ssl/live/XXXXWEBSITE_URLXXXX/privkey.pem

        SSLProtocol -ALL +TLSv1.2 +TLSv1.3
        SSLOpenSSLConfCmd DHParameters "/etc/ssl/certs/dhparam.pem"

#XXXXBASIC-AUTHXXXX        ErrorDocument 401 'Please visit https://XXXXAUTH-SERVER-URLXXXX to gain access' 

#XXXXPROXYXXXX         ProxyRequests Off
#XXXXPROXYXXXX         ProxyPreserveHost On
#XXXXPROXYXXXX Header add Set-Cookie "ROUTEID=.%{BALANCER_WORKER_ROUTE}e; path=/" env=BALANCER_ROUTE_CHANGED
#XXXXPROXYXXXX        <Proxy "balancer://webservers_https">
#XXXXPROXYXXXX            #XXXXBASIC-AUTHXXXX AuthType Basic
#XXXXPROXYXXXX            #XXXXBASIC-AUTHXXXX AuthName "Visit XXXXAUTH-SERVER-URLXXXX to generate a new password if you need to"
#XXXXPROXYXXXX            #XXXXBASIC-AUTHXXXX AuthUserFile /etc/apache2/.htpasswd
#XXXXPROXYXXXX            #XXXXBASIC-AUTHXXXX <RequireAny>
#XXXXPROXYXXXX            #XXXXBASIC-AUTHXXXX  Require ip XXXXVPC_IP_RANGEXXXX XXXXBUILD_MACHINE_IPXXXX
#XXXXPROXYXXXX            #XXXXBASIC-AUTHXXXX  Require valid-user
#XXXXPROXYXXXX            #XXXXBASIC-AUTHXXXX</RequireAny>
#XXXXPROXYXXXX
#XXXXPROXYXXXX            #xxxxWEBSERVERIPHTTPSxxxx
#XXXXPROXYXXXX
#XXXXPROXYXXXX            ProxySet stickysession=ROUTEID
#XXXXPROXYXXXX        </Proxy>


#XXXXS3_REDIRECTIONXXXX

#XXXXPROXYXXXX	      ProxyRequests Off
#XXXXPROXYXXXX        ProxyPreserveHost On
#XXXXPROXYXXXX    #XXXXBASIC-AUTH1XXXX     <Proxy *>
#XXXXOPEN-PROXYXXXX    #XXXXBASIC-AUTH1XXXX 
#XXXXWHITE-LISTXXXX    #XXXXBASIC-AUTH1XXXX 
#XXXXPROXYXXXX    #XXXXBASIC-AUTH1XXXX    </Proxy>
#XXXXPROXYXXXX        ProxyPass / "balancer://webservers_https/"  
#XXXXPROXYXXXX        ProxyPassReverse / "balancer://webservers_https/"


#XXXXPROXYXXXX   RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
#XXXXPROXYXXXX   RequestHeader set X-Forwarded-Host expr=%{HTTP_HOST}
#XXXXPROXYXXXX   RequestHeader set X-Forwarded-Proto "https"
#XXXXPROXYXXXX   RequestHeader set X-Forwarded-Port "443"
#XXXXPROXYXXXX   RequestHeader set X-Forwarding-For expr=%{HTTP_HOST}
    </VirtualHost>
</IfModule>
