ServerName XXXXWEBSITE_URLXXXX

#XXXXMODSECURITYXXXX

<IfModule mod_ssl.c>
    <VirtualHost *:443 [::]:443>
        DocumentRoot /var/www/html

        SSLEngine on
        SSLProxyEngine on
        SSLProxyVerify none
        SSLProxyCheckPeerCN off
        SSLProxyCheckPeerName off
        SSLProxyCheckPeerExpire off
        SSLCompression off

        SSLCertificateFile       XXXXHOMEXXXX/ssl/live/XXXXWEBSITE_URLXXXX/fullchain.pem
        SSLCertificateKeyFile    XXXXHOMEXXXX/ssl/live/XXXXWEBSITE_URLXXXX/privkey.pem

        SSLProtocol -ALL +TLSv1.2 +TLSv1.3
        SSLOpenSSLConfCmd DHParameters "/etc/ssl/certs/dhparam.pem"

#XXXXPROXYXXXX        <Proxy "balancer://webservers_https">
#XXXXPROXYXXXX            #XXXXBASIC-AUTHXXXX AuthType Basic
#XXXXPROXYXXXX            #XXXXBASIC-AUTHXXXX AuthName "Visit XXXXWEBSITE_URLXXXXX to generate a new password if you need to"
#XXXXPROXYXXXX            #XXXXBASIC-AUTHXXXX AuthUserFile /etc/apache2/.htpasswd
#XXXXPROXYXXXX            #XXXXBASIC-AUTHXXXX <RequireAny>
#XXXXPROXYXXXX            #XXXXBASIC-AUTHXXXX  Require ip XXXXVPC_IP_RANGEXXXX XXXXBUILD_MACHINE_IPXXXX
#XXXXPROXYXXXX            #XXXXBASIC-AUTHXXXX  Require valid-user
#XXXXPROXYXXXX            #XXXXBASIC-AUTHXXXX</RequireAny>
#XXXXPROXYXXXX
#XXXXPROXYXXXX            #xxxxWEBSERVERIPHTTPSxxxx
#XXXXPROXYXXXX
#XXXXPROXYXXXX            ProxySet lbmethod=byrequests
#XXXXPROXYXXXX        </Proxy>

#XXXXPROXYXXXX        ProxyPreserveHost On
#XXXXPROXYXXXX        ProxyPass / "balancer://webservers_https/"
#XXXXPROXYXXXX        ProxyPassReverse / "balancer://webservers_https"


#XXXXWIRE-GUARDXXXX		ProxyRequests Off
#XXXXWIRE-GUARDXXXX     ProxyPreserveHost On
#XXXXWIRE-GUARDXXXX     RequestHeader set Host "XXXXWEBSITE_URLXXXX"
#XXXXWIRE-GUARDXXXX
#XXXXWIRE-GUARDXXXX     <Proxy *>
#XXXXWIRE-GUARDXXXX         Order deny,allow
#XXXXWIRE-GUARDXXXX         Allow from all
#XXXXWIRE-GUARDXXXX     </Proxy>
#XXXXWIRE-GUARDXXXX
#XXXXWIRE-GUARDXXXX     ProxyPass / https://XXXXMAIN_WEBSITE_URLXXXX/
#XXXXWIRE-GUARDXXXX     ProxyPassReverse / https://XXXXMAIN_WEBSITE_URLXXXX/
#XXXXWIRE-GUARDXXXX     ProxyPassReverseCookieDomain XXXXWEBSITE_URLXXXX  XXXXMAIN_WEBSITE_URLXXXX
#XXXXWIRE-GUARDXXXX     RemoteIPHeader X-Forwarded-For


    </VirtualHost>
</IfModule>
