         ProxyRequests Off
         ProxyPreserveHost On
 Header add Set-Cookie "ROUTEID=.%{BALANCER_WORKER_ROUTE}e; path=/" env=BALANCER_ROUTE_CHANGED
        <Proxy "balancer://reverseproxy_https">

            #xxxxREVERSEPROXYIPHTTPSxxxx
#BalancerMember https://10.0.1.5:443 route=node1

            ProxySet stickysession=ROUTEID
        </Proxy>

              ProxyRequests Off
        ProxyPreserveHost On
        <Proxy *>
            Require all granted
        </Proxy>
        ProxyPass / "balancer://reverseproxy_https/"
        ProxyPassReverse / "balancer://reverseproxy_https/"

   RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
   RequestHeader set X-Forwarded-Host expr=%{HTTP_HOST}
   RequestHeader set X-Forwarded-Proto "https"
   RequestHeader set X-Forwarded-Port "443"
   RequestHeader set X-Forwarding-For expr=%{HTTP_HOST}
