#!/bin/sh
###########################################################################################################
# Description: This will accept an ip address that has been generated by a user inputing their laptop's
# IP address into the HTML form in reponse to a one time link to it
# Author : Peter Winter
# Date: 17/05/2017
######################################################################################################
# License Agreement:
# This file is part of The Agile Deployment Toolkit.
# The Agile Deployment Toolkit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# The Agile Deployment Toolkit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with The Agile Deployment Toolkit.  If not, see <http://www.gnu.org/licenses/>.
#######################################################################################################
#######################################################################################################
#set -x

MULTI_REGION="`${HOME}/utilities/config/ExtractConfigValue.sh 'MULTIREGION'`"
WEBSITE_URL="`${HOME}/utilities/config/ExtractConfigValue.sh 'WEBSITEURLORIGINAL'`"
SSH_PORT="`${HOME}/utilities/config/ExtractConfigValue.sh 'SSHPORT'`"
wireguard_port="`/usr/bin/expr ${SSH_PORT} + 1`"

if ( [ ! -d ${HOME}/runtime/authenticator ] )
then
        /bin/mkdir -p ${HOME}/runtime/authenticator 
fi

if ( [ -f /var/www/wire-guard/authentication-emails.dat ] )
then
        /bin/mv /var/www/wire-guard/authentication-emails.dat ${HOME}/runtime/authenticator/authentication-emails.dat
fi

if ( [ -f ${HOME}/runtime/authenticator/authentication-emails.dat ] )
then
        /bin/mv ${HOME}/runtime/authenticator/authentication-emails.dat ${HOME}/runtime/authenticator/emailaddresses.dat.incoming.$$
fi

config_updated="0"

if ( [ -f ${HOME}/runtime/authenticator/emailaddresses.dat.incoming.$$ ] )
then
        for email_address in `/bin/cat ${HOME}/runtime/authenticator/emailaddresses.dat.incoming.$$`
        do
                if ( [ ! -f /etc/wireguard/server_private.key ] )
                then
                        umask 077
                        /usr/bin/wg genkey > /etc/wireguard/server_private.key
                        /bin/chmod 600 /etc/wireguard/server_private.key
                        /bin/cat /etc/wireguard/server_private.key | /usr/bin/wg pubkey > /etc/wireguard/server_public.key

                        server_private_key="`/bin/cat /etc/wireguard/server_private.key`"

                        /bin/echo "[Interface]
                        PrivateKey = ${server_private_key}
                        Address = 10.0.0.1/16
                        ListenPort = ${wireguard_port}
                        SaveConfig = true
                        PersistentKeepAlive = 25 
                       
                        PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
                        PostUp = iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
                        PostUp = iptables -I INPUT 1 -i eth0 -p udp --dport ${wireguard_port} -j ACCEPT
                        PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE 
                        PostDown = iptables -D FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
                        PostDowb = iptables -I INPUT 1 -i eth0 -p udp --dport ${wireguard_port} -j ACCEPT" > /etc/wireguard/wg0.conf
                       # /bin/chmod 600 /etc/wireguard/wg0.conf
                        config_updated="1"
                fi

                if ( [ ! -f /etc/wireguard/client_${email_address}.conf ] )
                then
                        if ( [ -f /etc/wireguard/wg0.conf ] )
                        then
                                client_no="`/bin/grep "Peer" /etc/wireguard/wg0.conf | /usr/bin/wc -l`"
                                client_no="`/usr/bin/expr ${client_no} + 2`"
                        fi

                        /usr/bin/wg genkey > /etc/wireguard/client_${email_address}_private.key
                        /bin/cat /etc/wireguard/client_${email_address}_private.key | /usr/bin/wg pubkey > /etc/wireguard/client_${email_address}_public.key

                        # Get the keys and server info
                        new_client_private_key="`/bin/cat /etc/wireguard/client_${email_address}_private.key`"
                        new_client_public_key="`/bin/cat /etc/wireguard/client_${email_address}_public.key`"
                        server_public_key="`/bin/cat /etc/wireguard/server_public.key`"

                        twenty_four="`/usr/bin/expr ${client_no} / 255`"
                        iteration1="`/usr/bin/expr ${twenty_four} \* 255`" 
                        thirty_two="`/usr/bin/expr ${client_no} - ${iteration1}`"
                        sixteen="`/usr/bin/expr ${twenty_four} / 255`"
                        iteration2="`/usr/bin/expr ${sixteen} \* 255`" 
                        twenty_four="`/usr/bin/expr ${twenty_four} - ${iteration2}`"

                        # Add peer to server config
                        /bin/echo "[Peer]
                        PublicKey = ${new_client_public_key}
                        AllowedIPs = 10.${sixteen}.${twenty_four}.${thirty_two}/32" >> /etc/wireguard/wg0.conf 


                        # Create client config
                        /bin/echo "[Interface]
                        PrivateKey = ${new_client_private_key}
                        Address = 10.0.0.${client_no}/32
                        DNS = 1.1.1.1, 1.0.0.1 " > /etc/wireguard/client_${email_address}.conf

                        server_ips="`${HOME}/services/datastore/config/wrapper/ListFromDatastore.sh "config-reverseproxy"`"
                        
                        for server_ip in ${server_ips}
                        do
                                /bin/echo "[Peer]
                 PublicKey = ${server_public_key}
                 Endpoint = ${server_ip}:${wireguard_port}
                 PersistentKeepAlive = 25
                 AllowedIPs =  10.0.0.0/16
                 PersistentKeepalive = 25" >> /etc/wireguard/client_${email_address}.conf
                        done
                        config_updated="1"
                fi

                if ( [ ! -f /etc/wireguard/client_${email_address}.png ] )
                then
                        if ( [ ! -d /etc/wireguard/freshqrcodes ] )
                        then
                                /bin/mkdir /etc/wireguard/freshqrcodes
                        fi
                        /usr/bin/qrencode -t png -o /etc/wireguard/freshqrcodes/client_${email_address}.png -r /etc/wireguard/client_${email_address}.conf
                        config_updated="1"
                fi

                if ( [ "${config_updated}" = "1" ] )
                then
                        ${HOME}/services/datastore/operations/PutToDatastore.sh "wireguard-config" /etc/wireguard/freshqrcodes/client_${email_address}.png "qrcodes" "distributed" "no"
                        ${HOME}/services/datastore/operations/PutToDatastore.sh "wireguard-config" /etc/wireguard/client_${email_address}.conf "client" "distributed" "no"
                        ${HOME}/services/datastore/operations/PutToDatastore.sh "wireguard-config" /etc/wireguard/wg0.conf  "server" "distributed" "no"
                fi
                /bin/sed -i "/${email_address}$/d" ${HOME}/runtime/authenticator/emailaddresses.dat.incoming.$$

        done
fi

#/bin/cp ${HOME}/runtime/authenticator/qrcode/* /etc/wireguard/freshqrcodes
#/bin/cp ${HOME}/runtime/authenticator/client/* /etc/wireguard
#/bin/cp ${HOME}/runtime/authenticator/server/* /etc/wireguard


if ( [ -f ${HOME}/runtime/authenticator/emailaddresses.dat.incoming.$$ ] )
then
        /bin/rm ${HOME}/runtime/authenticator/emailaddresses.dat.incoming.$$
fi

