#!/bin/sh
###########################################################################################################
# Description: This will accept an ip address that has been generated by a user inputing their laptop's
# IP address into the HTML form in reponse to a one time link to it
# Author : Peter Winter
# Date: 17/05/2017
######################################################################################################
# License Agreement:
# This file is part of The Agile Deployment Toolkit.
# The Agile Deployment Toolkit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# The Agile Deployment Toolkit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with The Agile Deployment Toolkit.  If not, see <http://www.gnu.org/licenses/>.
#######################################################################################################
#######################################################################################################
#set -x

MULTI_REGION="`${HOME}/utilities/config/ExtractConfigValue.sh 'MULTIREGION'`"
WEBSITE_URL="`${HOME}/utilities/config/ExtractConfigValue.sh 'WEBSITEURLORIGINAL'`"
SSH_PORT="`${HOME}/utilities/config/ExtractConfigValue.sh 'SSHPORT'`"

if ( [ ! -d ${HOME}/runtime/authenticator ] )
then
        /bin/mkdir -p ${HOME}/runtime/authenticator 
fi

/bin/touch ${HOME}/runtime/authenticator/emailaddresses.dat

if ( [ -f /var/www/wire-guard/authentication-emails.dat  ] )
then
        /bin/mv /var/www/wire-guard/authentication-emails.dat ${HOME}/runtime/authenticator/emailaddresses.dat.incoming.$$
fi

if ( [ -f ${HOME}/runtime/authenticator/emailaddresses.dat.incoming.$$ ] )
then
        for email_address in `/bin/cat ${HOME}/runtime/authenticator/emailaddresses.dat.incoming.$$`
        do
                if ( [ ! -f /etc/wireguard/server_private.key ] )
                then
                        /usr/bin/wg genkey > /etc/wireguard/server_private.key
                        /bin/chmod 600 /etc/wireguard/server_private.key
                        /bin/cat /etc/wireguard/server_private.key | /usr/bin/wg pubkey > /etc/wireguard/server_public.key

                        server_private_key="`/bin/cat /etc/wireguard/server_private.key`"
                        wireguard_port="`/usr/bin/expr ${SSH_PORT} + 1`"

                        /bin/echo "[Interface]
                        PrivateKey = ${server_private_key}
                        Address = 10.0.0.1/24
                        ListenPort = ${wireguard_port}
                        PostUp = iptables -t nat -I POSTROUTING -o ens4 -j MASQUERADE
                        PostDown = iptables -t nat -D POSTROUTING -o ens4 -j MASQUERADE" > /etc/wireguard/wg0.conf

                        /bin/chmod 600 /etc/wireguard/wg0.conf
                fi

                if ( [ -f /etc/wireguard/wg0.conf ] )
                then
                        client_no="`/bin/grep "Peer" /etc/wireguard/wg0.conf | /usr/bin/wc -l`"
                        client_no="`/usr/bin/expr ${client_no} + 1`"
                fi
                
                /usr/bin/wg genkey > /etc/wireguard/client${client_no}_private.key"
                /bin/cat /etc/wireguard/client${client_no}_private.key" | /usr/bin/wg pubkey > /etc/wireguard/client${client_no}_public.key

                # Get the keys and server info
                new_client_private_key="`/bin/cat /etc/wireguard/client${client_no}_private.key`"
                new_client_public_key=="`/bin/cat /etc/wireguard/client${client_no}_public.key`"
                server_public_key="`/bin/cat /etc/wireguard/server_public.key`"
                server_ip="`${HOME}/utilities/processing/GetPublicIP.sh`"

                # Add peer to server config
                /bin/echo "[Peer]
                PublicKey = ${new_client_public_key}
                AllowedIPs = 10.0.0.${client_no}/32" >> /etc/wireguard/wg0.conf 


                # Create client config
                /bin/echo "[Interface]
                PrivateKey = ${new_client_private_key}
                Address = 10.0.0.${client_no}/32
                DNS = 1.1.1.1, 1.0.0.1

                [Peer]
                PublicKey = ${server_public_key}
                Endpoint = ${server_ip}:${wireguard_port}
                AllowedIPs = 0.0.0.0/0
                PersistentKeepalive = 25" > /etc/wireguard/client-${email_address}.conf
        done
fi
