#!/bin/sh
###########################################################################################################
# Description: This obtains the list of emails generated by the authenticators that require wireguard configurations
# to be generated for them
# Author : Peter Winter
# Date: 17/05/2017
######################################################################################################
# License Agreement:
# This file is part of The Agile Deployment Toolkit.
# The Agile Deployment Toolkit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# The Agile Deployment Toolkit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with The Agile Deployment Toolkit.  If not, see <http://www.gnu.org/licenses/>.
#######################################################################################################
#######################################################################################################
#set -x

if ( [ ! -f ${HOME}/runtime/wire-guard/SENT_NOTIFICATION_EMAIL ] )
then
        if ( [ "`${HOME}/services/datastore/operations/ListFromDatastore.sh "wire-guard-emails" "SENT_NOTIFICATION_EMAIL"`" = "" ] )
        then
                exit
        else
                /bin/touch ${HOME}/runtime/wire-guard/SENT_NOTIFICATION_EMAIL
        fi
fi

if ( [ ! -d ${HOME}/runtime/wire-guard/emails/incoming ] )
then
        /bin/mkdir -p ${HOME}/runtime/wire-guard/emails/incoming
fi

${HOME}/services/datastore/operations/SyncFromDatastore.sh "wire-guard-emails" "${HOME}/runtime/wire-guard/emails/incoming"
/bin/cat ${HOME}/runtime/wire-guard/emails/incoming/authentication-emails* > ${HOME}/runtime/wire-guard/emails/incoming/all_authentication-emails.dat
/usr/bin/sort -u ${HOME}/runtime/wire-guard/emails/incoming/all_authentication-emails.dat | /bin/sed '/^$/d' >  ${HOME}/runtime/wire-guard/emails/incoming/all_authentication-emails.dat.$$
/bin/mv ${HOME}/runtime/wire-guard/emails/incoming/all_authentication-emails.dat.$$ ${HOME}/runtime/wire-guard/emails/incoming/all_authentication-emails.dat

if ( [ ! -d ${HOME}/runtime/wire-guard/emails/processing ] )
then
        /bin/mkdir -p ${HOME}/runtime/wire-guard/emails/processing
fi

/bin/touch ${HOME}/runtime/wire-guard/emails/incoming/all_authentication-emails.dat

if ( [ -f ${HOME}/runtime/wire-guard/emails/processing/processed_authentication_emails.dat ] )
then
        /bin/grep -vf ${HOME}/runtime/wire-guard/emails/processing/processed_authentication_emails.dat ${HOME}/runtime/wire-guard/emails/incoming/all_authentication-emails.dat > ${HOME}/runtime/wire-guard/emails/processing/to_process_authentication_emails.dat 
else
        /bin/cp ${HOME}/runtime/wire-guard/emails/incoming/all_authentication-emails.dat ${HOME}/runtime/wire-guard/emails/processing/to_process_authentication_emails.dat
fi
